<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:MSM="http://www.myshoppingmall.com/1.0" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmi:id="_aYoAEDYbEeqL8ZdbWUo3jw" type="MyShoppingMall" name="final.mmd" measurementUnit="Pixel">
  <children xmi:type="notation:Shape" xmi:id="_cMTkMDYbEeqL8ZdbWUo3jw" type="2006" fontName="Ubuntu">
    <children xmi:type="notation:DecorationNode" xmi:id="_cMULQDYbEeqL8ZdbWUo3jw" type="5007"/>
    <children xmi:type="notation:BasicCompartment" xmi:id="_cMULQTYbEeqL8ZdbWUo3jw" type="7005">
      <children xmi:type="notation:Shape" xmi:id="_kfSHADYbEeqL8ZdbWUo3jw" type="3006" fontName="Ubuntu">
        <children xmi:type="notation:DecorationNode" xmi:id="_kfTVIDYbEeqL8ZdbWUo3jw" type="5013"/>
        <element xmi:type="MSM:Employee" href="final.mm#//@shops.0/@employees.0"/>
        <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kfSHATYbEeqL8ZdbWUo3jw" x="38" y="16" width="121" height="49"/>
      </children>
    </children>
    <children xmi:type="notation:BasicCompartment" xmi:id="_cMUyUDYbEeqL8ZdbWUo3jw" type="7011">
      <children xmi:type="notation:Shape" xmi:id="_gC8ekDYbEeqL8ZdbWUo3jw" type="3002" fontName="Ubuntu">
        <children xmi:type="notation:DecorationNode" xmi:id="_gC-TwDYbEeqL8ZdbWUo3jw" type="5012"/>
        <children xmi:type="notation:BasicCompartment" xmi:id="_gC-TwTYbEeqL8ZdbWUo3jw" type="7007">
          <children xmi:type="notation:Shape" xmi:id="_ipAh4DYbEeqL8ZdbWUo3jw" type="3003" fontName="Ubuntu">
            <children xmi:type="notation:DecorationNode" xmi:id="_ipCXEDYbEeqL8ZdbWUo3jw" type="5011"/>
            <children xmi:type="notation:BasicCompartment" xmi:id="_ipCXETYbEeqL8ZdbWUo3jw" type="7008">
              <children xmi:type="notation:Shape" xmi:id="_mvAt8DYbEeqL8ZdbWUo3jw" type="3004" fontName="Ubuntu">
                <children xmi:type="notation:DecorationNode" xmi:id="_mvB8EDYbEeqL8ZdbWUo3jw" type="5010"/>
                <children xmi:type="notation:BasicCompartment" xmi:id="_mvCjIDYbEeqL8ZdbWUo3jw" type="7009"/>
                <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="_mvAt8TYbEeqL8ZdbWUo3jw"/>
                <element xmi:type="MSM:Category" href="final.mm#//@shops.0/@storages.0/@items.0/@items"/>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mvAt8jYbEeqL8ZdbWUo3jw" x="14" y="10" width="97" height="45"/>
              </children>
            </children>
            <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="_ipAh4TYbEeqL8ZdbWUo3jw"/>
            <element xmi:type="MSM:Item" href="final.mm#//@shops.0/@storages.0/@items.0"/>
            <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ipAh4jYbEeqL8ZdbWUo3jw" x="14" y="8" width="145" height="111"/>
          </children>
        </children>
        <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="_gC8ekTYbEeqL8ZdbWUo3jw"/>
        <element xmi:type="MSM:Storage" href="final.mm#//@shops.0/@storages.0"/>
        <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gC8ekjYbEeqL8ZdbWUo3jw" x="14" y="-7" width="241" height="165"/>
      </children>
    </children>
    <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="_cMTkMTYbEeqL8ZdbWUo3jw"/>
    <element xmi:type="MSM:Specialistic" href="final.mm#//@shops.0"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cMTkMjYbEeqL8ZdbWUo3jw" x="168" y="48" width="313" height="385"/>
  </children>
  <children xmi:type="notation:Shape" xmi:id="_tor7gDYbEeqL8ZdbWUo3jw" type="2005" fontName="Ubuntu">
    <children xmi:type="notation:DecorationNode" xmi:id="_totJoDYbEeqL8ZdbWUo3jw" type="5006"/>
    <children xmi:type="notation:BasicCompartment" xmi:id="_totJoTYbEeqL8ZdbWUo3jw" type="7004">
      <children xmi:type="notation:Shape" xmi:id="_wwfZ8DYbEeqL8ZdbWUo3jw" type="3006" fontName="Ubuntu">
        <children xmi:type="notation:DecorationNode" xmi:id="_wwgoEDYbEeqL8ZdbWUo3jw" type="5013"/>
        <element xmi:type="MSM:Employee" href="final.mm#//@shops.1/@employees.0"/>
        <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wwfZ8TYbEeqL8ZdbWUo3jw" x="38" y="16" width="121" height="97"/>
      </children>
    </children>
    <children xmi:type="notation:BasicCompartment" xmi:id="_totJojYbEeqL8ZdbWUo3jw" type="7010">
      <children xmi:type="notation:Shape" xmi:id="_1CBgkDYbEeqL8ZdbWUo3jw" type="3002" fontName="Ubuntu">
        <children xmi:type="notation:DecorationNode" xmi:id="_1CBgkzYbEeqL8ZdbWUo3jw" type="5012"/>
        <children xmi:type="notation:BasicCompartment" xmi:id="_1CCHoDYbEeqL8ZdbWUo3jw" type="7007">
          <children xmi:type="notation:Shape" xmi:id="_6AJAYDYbEeqL8ZdbWUo3jw" type="3003" fontName="Ubuntu">
            <children xmi:type="notation:DecorationNode" xmi:id="_6AKOgDYbEeqL8ZdbWUo3jw" type="5011"/>
            <children xmi:type="notation:BasicCompartment" xmi:id="_6AKOgTYbEeqL8ZdbWUo3jw" type="7008"/>
            <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="_6AJAYTYbEeqL8ZdbWUo3jw"/>
            <element xmi:type="MSM:Item" href="final.mm#//@shops.1/@storages.0/@items.0"/>
            <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6AJAYjYbEeqL8ZdbWUo3jw" x="14" y="9" width="73" height="25"/>
          </children>
        </children>
        <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="_1CBgkTYbEeqL8ZdbWUo3jw"/>
        <element xmi:type="MSM:Storage" href="final.mm#//@shops.1/@storages.0"/>
        <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1CBgkjYbEeqL8ZdbWUo3jw" x="38" y="9" width="121" height="116"/>
      </children>
    </children>
    <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="_tor7gTYbEeqL8ZdbWUo3jw"/>
    <element xmi:type="MSM:Branded" href="final.mm#//@shops.1"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tor7gjYbEeqL8ZdbWUo3jw" x="648" y="48" width="289" height="337"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_aYoAETYbEeqL8ZdbWUo3jw"/>
  <element xmi:type="MSM:Mall" href="final.mm#/"/>
</notation:Diagram>
